model = "gpt-5-codex"
model_reasoning_effort = "medium"
hide_agent_reasoning = true
network_access = true

[features]
web_search_request = true

[mcp_servers.chrome-devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest", "--headless=true"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]

[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "codex"]

[mcp_servers.vibe-kanban]
command = "npx"
args = ["-y", "vibe-kanban", "--mcp"]
